name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm build
    - run: npm test
    - name: check format
      uses: DoozyX/clang-format-lint-action@v0.5
      with: { extensions: 'ts' }
