name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: start X server
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo "::set-env name=DISPLAY:::99"
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm build
    - run: npm test
    - name: check format
      uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: 'src test'
        extensions: 'ts'
